title: Welcome to IMPART Academy
description: Innovative Methods for Patient Assessment using Real-world digital Technology
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
github:
  is_project_page: false